name: Run UI Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 4: Install Chrome and Chromedriver
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          wget https://storage.googleapis.com/chrome-for-testing-public/132.0.6834.159/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64/chrome /usr/local/bin/
          sudo chmod +x /usr/local/bin/chrome

      # Step 5: Verify Chrome and Chromedriver Versions
      - name: Verify Chrome and Chromedriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      # Step 6: Kill Chrome Processes
      - name: Kill Chrome Processes
        run: pkill -f chrome || true

      # Step 7: Create a temporary user data directory for Chrome
      - name: Create Temporary Chrome User Data Directory
        run: mkdir -p /tmp/chrome-user-data

      # Step 8: Run UI Tests
      - name: Run UI Tests
        run: ./gradlew remote --no-daemon --console=plain -Dcountry=us -Ddevice=desktop -Dspring.profiles.active=desktop,us -Dsuite=regression -Dthreads=2 -Dselenide.headless=true -Dselenide.options="--user-data-dir=/tmp/chrome-user-data"